services:
  frontend:
    container_name: pepe-constructor-frontend-temp
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://backend:5000
    command: npm run dev
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      # Usar la conexión directa en lugar del pooler para desarrollo
      - DATABASE_URL=postgresql://postgres.fklgqyxbxtiodmpjuvuz:TZEI28U9DIRRDlQ9@aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
      - DIRECT_URL=postgresql://postgres.fklgqyxbxtiodmpjuvuz:TZEI28U9DIRRDlQ9@aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
