# Usar una imagen base específica para la arquitectura
FROM --platform=linux/amd64 node:20-alpine

WORKDIR /app

# Copiar archivos de configuración
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Generar el cliente Prisma durante el inicio
RUN npm install -g prisma
RUN npx prisma generate

# Exponer puerto
EXPOSE 5000

# Script para inicializar y ejecutar la aplicación
CMD ["sh", "-c", "npx prisma generate && npx prisma db pull && npm run dev"]