# Usar una imagen base específica para la arquitectura
FROM --platform=linux/amd64 node:20-alpine

WORKDIR /app

# Copiar archivos de configuración
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar prisma y generar cliente
COPY prisma ./prisma/
RUN npx prisma generate --schema=./prisma/schema.prisma

# Copiar el resto del código
COPY . .

# Exponer puerto
EXPOSE 5000

# Comando para iniciar en modo desarrollo
CMD ["npm", "run", "dev"]